name: Container registry cleanup flow.
run-name: Cleaning up old images
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5.0.0
        with:
          delete-only-untagged-versions: true
          package-name: 'custampimages/ampcust'
          package-type: 'container'
      - uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'custampimages/ampcust'
          package-type: 'container'
          min-versions-to-keep: 9
          ignore-versions: '^srb2$|^srb2kart$|^ringracers$'
